name: face_net_authentication
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pu`b.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.9.4+68

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4
  # tflite_flutter: ^0.9.0

  permission_handler: ^11.0.1

  #* Background service
  # workmanager: ^0.5.1

  #* Machine Learrning
  # path_provider: ^2.0.9
  # path: ^1.8.0
  # google_ml_kit: ^0.13.0
  # image: ^3.0.2
  # # iOS : microphone access required
  # camera: ^0.9.4+19

  #* Maps
  geocoding: ^3.0.0
  geofence_service: ^5.0.0

  #* UI
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.0
  dropdown_search: ^5.0.6
  flash: ^3.0.5+1
  flutter_keyboard_visibility: ^6.0.0
  flutter_svg: ^2.0.0
  google_fonts: 6.1.0
  lottie: ^2.7.0

  #* Network
  alice: ^0.4.1
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.2.0-beta-1
  url_launcher: ^6.1.5

  #* Dart data class
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  # riverpod_generator: ^2.1.5

  #* Code generator
  riverpod: ^2.4.3
  riverpod_annotation: ^2.2.0

  #* State management
  flutter_hooks: ^0.20.4
  hooks_riverpod: ^2.4.3

  #* Service Locator
  get_it: ^7.2.0

  #* Logging
  logging: ^1.1.0

  #* Routing
  go_router: ^13.2.0

  #* Persistent storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.0
  # sqflite: ^2.0.2

  #* UUID
  uuid: ^4.2.2

  #* Versioning
  package_info_plus: ^4.1.0
  upgrader: ^9.0.0

  #* Networking
  flutter_inappwebview: ^6.0.0
  connectivity_plus: ^5.0.2
  ntp: ^2.0.0

  #* Firebase
  firebase_core: ^2.24.2
  firebase_remote_config: ^4.3.8
  firebase_analytics: ^10.8.0

  #* Misc
  collection: ^1.16.0
  dartz: ^0.10.1
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  #* Code generators
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.13
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  riverpod_generator: ^2.3.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
